In [3497]:
reddit = praw.Reddit(client_id='80odTHDj012Wqw',
                     client_secret='NlEVuqPDwOTz5kG8jfKFyScG1oc',
                     user_agent='metis_c ')

In [3498]:
print(reddit.read_only)

True


In [3499]:
for submission in reddit.subreddit('learnpython').hot(limit=10):
    print(submission.title)

Ask Anything Monday - Weekly Thread
What was something you struggled with to learn?
Newb Question about Random functions
Why does pycharm not seem that common in data science/research circles?
Become a Part-time python intern?
Having trouble with google drive api
Click a random search result from google search results python
Type check
Anyone here taken SEC573?
Python syntax rules


In [3500]:
random_submission = reddit.subreddit('all').random()

In [3501]:
random_submission

Submission(id='99ghm8')

In [3502]:
comments =[]
random_submission.comments.replace_more(limit=None)
for comment in random_submission.comments.list():
    comments.append(comment.body)

In [3503]:
emoji_comments = []
for comment in comments:
    if text_has_emoji(comment) == True:
        emoji_comments.append(comment)
    

In [3504]:
import time
import emoji

def text_has_emoji(text):
    for character in text:
        if character in emoji.UNICODE_EMOJI:
            return True
    return False

In [3505]:
t_end = time.time() + 60 * 240
while time.time() < t_end:
    random_submission = reddit.subreddit('all').random()
    random_submission.comments.replace_more(limit=None)
    for comment in random_submission.comments.list():
        if text_has_emoji(comment.body) == True:
            emoji_comments.append(comment.body)

In [3506]:
emoji_dict = dict(zip(range(len(emoji_comments)), emoji_comments))

In [3507]:
len(emoji_dict)

6258

In [3508]:
import json
with open('emoji_comments5.json', 'w') as fp:
    json.dump(emoji_dict, fp)

In [3509]:
comments = pd.read_json('emoji_comments.json', orient='records', typ = 'series')
comments0 = pd.read_json('emoji_comments0.json', orient='records', typ = 'series')
comments1 = pd.read_json('emoji_comments1.json', orient='records', typ = 'series')
comments2 = pd.read_json('emoji_comments2.json', orient='records', typ = 'series')
comments3 = pd.read_json('emoji_comments3.json', orient='records', typ = 'series')
comments4 = pd.read_json('emoji_comments4.json', orient='records', typ = 'series')
comments5 = pd.read_json('emoji_comments5.json', orient='records', typ = 'series')


In [3510]:
comments_all = pd.concat([comments, comments0, comments1, comments2, comments3, comments4, comments5], ignore_index=True)

In [3511]:
comments_all.drop_duplicates(inplace=True)

In [3512]:
test = comments_all[0]

In [3513]:
import emoji
import re
emoji_pattern = emoji.get_emoji_regexp()
matched_emoji = re.findall(emoji_pattern, test)

In [3514]:
from nltk.tokenize import word_tokenize
test_text = re.sub(emoji_pattern, '', test)
tokenizer = word_tokenize(test_text)

In [3515]:
raw = []
text = []
emoji_list = []
both = []
for comment in comments_all:
    raw.append(comment)
    token_text = re.sub(emoji_pattern, '', comment)
    tokenizer = word_tokenize(token_text)
    text.append(tokenizer)
    matched_emoji = re.findall(emoji_pattern, comment)
    emoji_list.append(matched_emoji)
    combined = tokenizer + matched_emoji
    both.append(combined)

In [3516]:
test_df = pd.DataFrame({'raw': raw,
     'text': text,
     'emoji': emoji_list,
     'both': both
    })


In [3517]:
from textblob import TextBlob
sentiments = []
for words in text:
    one_text = " ".join(words)
    sentiments.append(TextBlob(one_text).sentiment)

In [3518]:
sentiments = pd.Series(sentiments)

In [3519]:
test_df['sentiment'] = sentiments.values

In [3520]:
custom_emotions = pd.read_csv('NRC-Emotion-Lexicon-Wordlevel-v0.92.tsv', sep='\t', header=None)

In [3521]:
dict_frame = custom_emotions.iloc[:,[0,2]]

In [3522]:
dict_frame.columns = ['word', 'bin']

In [3523]:
dict_frame0 = dict_frame.groupby('word').agg('bin').apply(list)

In [3524]:
emotion_dict = dict(zip(dict_frame0.index, dict_frame0.values))

In [3525]:
phrases = list(test_df['text'])

In [3526]:
emotion_arrays = []
for phrase in phrases:
    phrase_sent = np.array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])
    for word in phrase:
        if word in emotion_dict.keys():
            phrase_sent += np.array(emotion_dict[word])
    emotion_arrays.append(phrase_sent)

In [3527]:
test_df['emotion'] = emotion_arrays

In [3528]:
test_df

raw  \
0                                             😍 the best   
1                                     Benefits us too. 😍   
2                            Nice sunflower sundress 🌻😍🌻   
3      Wonderful, as if a field of sunflowers 🌻 had a...   
4      Summer is over and I didn’t see a single sundr...   
5      Pops like a popsicle 😋😋😝😝 I don't knw what I a...   
6       *🎵Shot through the heart, and your to blame...🎵*   
7      Is it just me or does every archer start with ...   
8        OMG REALLY???!!! I DIDN'T REALISE!! 🤔🤔🤔😮😮😮😮 /s    
9      So the doctor could determine which antivenom ...   
10     Yeah he wouldn’t. I used to do archery when I ...   
11     This seems to be the new, ‘who hurt you’ comme...   
12            it's me when I see something delicious!😆😆😆   
13     I like how turns around and is like "what? Can...   
14                                 Well feed him then 🅱️   
15     LOL Saudi Arabia is the literal dogshit of the...   
16     wow this is getting fun xD\n\nCan we just laug...   
17     I’m not sure if you’re being sarcastic but i a...   
18     I think we may have worked in the same picu 😊....   
19     We did! And there’s one fellow in particular w...   
20                      Or OP is about to be murdered. 😬   
21     😭😭😭 but shit I kinda wanna try this with vape ...   
22                            COFFEE = GREAT FOR TASTE 👍   
23     The guy out front gives me the heebie jeebies ...   
24                                 Yes!!! Let’s go!!! ❤️   
25     Declaration of economic war will be considered...   
26                            Russian puppet confirmed 😎   
27                        Hey Kremlin! 🖕🏻\nThat is all.    
28     “Yeah b-but they uh, interfered in our electio...   
29     The sanctions are what Trump has fought agains...   
...                                                  ...   
12421                                 This got me good 😂   
12422  🎶 pasted all their hopes on him🎶  \n🎵 like the...   
12423               That would be the cherry on top!🍦🍧🍨🍸   
12424                                             Lmao 🍿   
12425           I laughed so hard. Thank you for this ❤️   
12426                Hey! Lol I work at that newspaper 😂   
12427  Damn, I was 3 hours late. I thought of this im...   
12428  It's fine though, I only have to work another ...   
12429  From what someone said who worked there at the...   
12430                             "Plan'it Fitn'ess" 👉😀👉   
12431  Maybe I wasn’t clear, but I meant ‘yeah, I do ...   
12432  Americunts😤👊 get **Absolutely** 🙌👌 *destroyed*...   
12433                                            Stop 🛑    
12434                                              😭😭😭😭❤   
12435         What a start to the day, favourite treat 🤗   
12436          Jeez are you really that whipped?? Lol 😂    
12437                              /r/shitredditsays 😂😂😂   
12438                                      Brett Rossi 💕   
12439    Yes. She was the first “Pornstar” I ever shot 💕   
12440  Thought so, but I couldn’t remember her name! ...   
12441                                     Ummmmm ☺️ lol    
12442                                            Bless 💕   
12443  I was amazed on this...I repeat on watching ov...   
12444                                      Fus ro dah 😀    
12445            👏👏👏  coolest thing I've seen in awhile.   
12446                Is it weird that I want to watch? 🤔   
12447                        I can do that too. ⬇️↙️⬅️+👣   
12448                 Hitman pupper spares no one\nOwO 🐺   
12449  At like 29 seconds dude missed the kick and th...   
12450  Agreed. As far as cops go I've never actually ...   

                                                    text  \
0                                            [the, best]   
1                                 [Benefits, us, too, .]   
2                            [Nice, sunflower, sundress]   
3      [Wonderful, ,, as, if, a, field, of, sunflower...   
4      [Summer, is, over, and, I

In [3529]:
emotions = ['anger', 'anticipation', 'disgust', 'fear', 'joy', 'negative', 'positive', 'sadness', 'surprise', 'trust']

In [3530]:
phrases = []
for phrase in test_df['emoji']:
    phrase = [char for char in phrase if char in emoji.UNICODE_EMOJI]
    one_text = "".join(phrase)
    phrases.append(one_text)

In [3531]:
from sklearn.feature_extraction.text import TfidfVectorizer
tf = TfidfVectorizer(ngram_range=(1, 4), analyzer = 'char', max_df = 0.01)
X = tf.fit_transform(phrases)

In [3532]:
from sklearn.decomposition import TruncatedSVD

lsa_tfidf = TruncatedSVD(n_components=40)

lsa_tfidf_data = lsa_tfidf.fit_transform(X)

In [3533]:
len(lsa_tfidf_data)

12451

In [3534]:
from sklearn.cluster import DBSCAN
db = DBSCAN(eps=0.02, min_samples=200).fit(emotion_arrays)

In [3535]:
core_samples_mask = np.zeros_like(db.labels_, dtype=bool)
core_samples_mask[db.core_sample_indices_] = True
labels = db.labels_.tolist()

In [3536]:
len(labels)

12451

In [3537]:
n_clusters_ = len(set(labels)) - (1 if -1 in labels else 0)

In [3538]:
n_clusters_

4

In [3539]:
unique_labels = set(labels)
unique_labels

{-1, 0, 1, 2, 3}

In [3540]:
# from sklearn.cluster import KMeans

# num_clusters = 8

# km = KMeans(n_clusters=num_clusters)

# %time km.fit(emotion_arrays)

# clusters = km.labels_.tolist()

In [3541]:
# clusters = km.labels_.tolist()

In [3542]:
comments = { 'text': list(test_df['text']), 'emoji': list(test_df['emoji']), 'emotion': list(test_df['emotion']), 'cluster': labels}

frame = pd.DataFrame(comments , columns = ['text',  'emoji', 'emotion', 'cluster'])

In [3543]:
frame['cluster'].value_counts()

 0    5990
-1    5507
 3     471
 2     242
 1     241
Name: cluster, dtype: int64

In [3544]:
cluster0 = frame.loc[frame['cluster'] == 0]
cluster1 = frame.loc[frame['cluster'] == 1]
cluster2 = frame.loc[frame['cluster'] == 2]
cluster3 = frame.loc[frame['cluster'] == 3]

In [3545]:
cluster_frames = [cluster0, cluster1, cluster2, cluster3, cluster4]

In [3546]:
def get_column_avg(column):
    avg_vector = []
    for i in list(range(len(column[0]))):
        avg_vector.append(sum([e[i] for e in column])/len(column))
    return np.array(avg_vector)

In [3547]:
results = []
for cluster in cluster_frames:
    results.append(get_column_avg(list(cluster['emotion'])))

In [3548]:
emotions

['anger',
 'anticipation',
 'disgust',
 'fear',
 'joy',
 'negative',
 'positive',
 'sadness',
 'surprise',
 'trust']

In [3549]:
results

[array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]),
 array([0., 0., 0., 0., 0., 0., 1., 0., 0., 1.]),
 array([0., 0., 0., 0., 1., 0., 1., 0., 0., 0.]),
 array([0., 0., 0., 0., 0., 0., 1., 0., 0., 0.]),
 array([0., 1., 0., 0., 1., 0., 1., 0., 0., 1.])]

In [3550]:
from sklearn.naive_bayes import GaussianNB

clf = GaussianNB()
clf.fit(X.toarray(), frame['cluster'])

GaussianNB(priors=None)

In [3551]:
names = np.asarray(tf.get_feature_names())

In [3552]:
np.argsort(clf.theta_, axis=1)[:,:-5:-1]

array([[20116, 19472, 24801, 21962],
       [19778,  9174, 12915, 11810],
       [20874, 21795, 24801, 23028],
       [20477,  3296, 20327, 15161],
       [22710, 16254, 12712, 21172]])

In [3553]:
most_important_per_cluster_index = np.argsort(clf.theta_, axis=1)[:,:-5:-1]
for index,cluster in enumerate(most_important_per_cluster_index):
    msg = ', '.join(names[cluster])
    print(f'Cluster {index:2d}. {msg}')

Cluster  0. 😆, 😀, 🤔🤔, 😬
Cluster  1. 😂😂😂😂, 🎶🎶, 👏👏, 👀
Cluster  2. 😒, 😩, 🤔🤔, 🙌
Cluster  3. 😍😍, ❤❤, 😋, 💕
Cluster  4. 🙂, 💯, 👍🏻, 😛
